apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: opossum
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opossum
    app.kubernetes.io/part-of: opossum
  name: opossum
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: opossum
status:
  loadBalancer: {}
